version: 2

jobs:
  test_7.1:
    working_directory: ~/laravel-testing-utils
    docker:
    - image: circleci/php:7.1-cli
    steps:
    - checkout
    - run: sudo composer self-update --no-progress --no-interaction
    - run: composer install --no-progress --no-interaction --prefer-dist
    - run: composer check

  test_7.2:
    working_directory: ~/laravel-testing-utils
    docker:
    - image: circleci/php:7.2-cli
    steps:
    - checkout
    - run: sudo composer self-update --no-progress --no-interaction
    - run: composer install --no-progress --no-interaction --prefer-dist
    - run: composer check

workflows:
  version: 2
  test:
    jobs:
    - test_7.1
    - test_7.2
